- name: My first play
  hosts: virtualmachines
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: Copy docker-compose to remote server
     ansible.builtin.copy:
       src: "{{ playbook_dir }}/app/docker-compose.yaml"
       dest: /tmp/docker-compose.yaml
   - name: docker-compose up in the remote server
     community.docker.docker_compose:
       project_src: "/tmp"
       files:
        - docker-compose.yaml
       services:
       state: "present"
   - name: docker-compose stop in the remote server
     community.docker.docker_compose:
       project_src: /tmp
       files:
        - docker-compose.yaml
       services:
       state: "absent"
