- name: stop services
  hosts: virtualmachines
  tasks:
   - name: docker-compose stop in the remote server
     community.docker.docker_compose:
       project_src: /tmp
       files:
        - docker-compose.yaml
       services:
       state: "absent"

