version: "3.9"
services:
 nginx:
   networks:
     - wp-network
   build: ./nginx
   ports:
     - "80:80"
     - "443:443"
 mysql:
   networks:
     - wp-network
   image: mysql:latest
   volumes:
      - ./mysql:/var/lib/mysql
   env_file:
      - .env
   ports:
      - "3306:3306"
 wordpress:
   networks:
     - wp-network
   image: wordpress:6.1.1-fpm-alpine
   depends_on:
      - mysql
   links:
      - mysql
   env_file:
      - .env
   ports:
      - "9000:9000"
volumes:
  mysql:
networks:
  wp-network:
