version: "3.9"
services:
 mysql:
   networks:
     - wp-network
   image: mysql:latest
   volumes:
      - ./mysql:/var/lib/mysql
   env_file:
      - .env
   ports:
      - "3306:3306"
 wordpress:
   container_name: wordpress
   networks:
     - wp-network
   image: wordpress:6.1.1-fpm-alpine
   depends_on:
      - mysql
   env_file:
      - .env
   ports:
      - "9000:9000"
   volumes:
      - /tmp/app/wordpress/html:/var/www/html
 nginx:
   networks:
     - wp-network
   build: ./nginx
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - /tmp/app/wordpress/html:/var/www/html
   depends_on:
     - wordpress
volumes:
  mysql:
networks:
  wp-network:
