version: "3.9"
services:
 mysql:
   container_name: mysql
   networks:
     - wp-network
   image: mysql:latest
   volumes:
     - ./mysql:/var/lib/mysql
   env_file:
      - .env
   ports:
     - "127.0.0.1:3306:3306"
 wordpress:
   container_name: wordpress
   networks:
     - wp-network
   image: wordpress:6.1.1-fpm
   depends_on:
      - mysql
   env_file:
      - .env
   ports:
     - "127.0.0.1:9000:9000"
   volumes:
      - /tmp/app/wordpress/html:/var/www/html
 nginx:
   networks:
     - wp-network
   build: ./nginx
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - /tmp/app/wordpress/html:/var/www/html
     - /tmp/app/phpmyadmin/htm:/usr/share/phpmyadmin
   depends_on:
     - wordpress
     - phpmyadmin
 phpmyadmin:
   container_name: phpmyadmin
   networks:
     - wp-network
   build: ./phpmyadmin
   command: ["sh", "-c", "cp -r /var/www/html/. /usr/share/phpmyadmin && php-fpm"]
   depends_on:
     - mysql
   ports:
     - "127.0.0.1:9090:9000"
   env_file:
     - .env
   volumes:
     - /tmp/app/phpmyadmin/htm:/usr/share/phpmyadmin
     - ./mysql:/var/lib/mysql
volumes:
  mysql:
networks:
  wp-network:
